language: ruby
cache: bundler
rvm:
- 2.2.5
addons:
  postgresql: '9.4'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:test:prepare
script:
- bundle exec rake spec
after_success:
- bundle exec codeclimate-test-reporter
- git pull
- git remote add flynn https://seza443:$FLYNN_KEY@git.yxvj.flynnhub.com/geohealth-happibackend-master.git
- git push flynn master
notifications:
  slack:
    secure: Xaooc8J/JccmRvuPBok2ocHoby0PF7rfWTbt4TMqDSNvxjy/d7cwOfw1ijjjX8wA6n8oTENGsEXXWizXLh9y2E+1iS/UR1AlMENHbUw+9v0pcopbJcSZfI0k69QjwHmggfmYEjRHJxqxiEDkLTA4w4qeagTg9CH56f8npoojDf1zE4KVF1bjwMg+3U7Pv7VNubWORX9Gp91I6GqVvfVDnLGlejh/VHyoCp+p8m05fish81nDI2QPex7f+2faEqXhEQAGbhifJvoVMaQ2ybJzYbjv28vuslXr6ju7QJkHkmad6b+mfvo+lJb/KQHb0RbB75+P3rDQQJWHEkFelkgTF9qKjXgl1arZvLGYzlYYbJeAnBylf8u0xXEld7a9+HQdY3BMjaXu+LlSaxZwAG7pQ5S6CIK4g4c/WkRQwAWFoeuNapAZ8uZO7lL0IonizuuBxYv2GTyK6Eox+KPtntI2Zr6s/mhZVxUH3ddvbKiYbNuIvVkzrK5Fz5M06G+dsFrs6mmyIw9xBwn/A4xWqqssG1OVYafMI+tyn6l99MTla30OfSO+2pHLu8Z8VyNYMDn8frt0rHiqd49JZwhCs/xVQKvE1BUJ7kf+ULOHfq/9baZQOqf5J/l5EbnJg/RckL0899nrkp3u9r/1e9xbZci6OltPg0kUJ+7ilPczVIC3C/Q=
env:
  global:
    secure: RQ8x+kqz41n8+DSLVfmar85FkiYd7eXTLrl49WagIc+Cufe5T/M4fbm+86yk9JoaQJ3a4/+s7zp9FqvRzKrHEIjO5KJ80kkp8G6vmgMhoL3zwNhMgSTNfI4b/cYEy6HSNRK4fzw1LZFNtGYo9XW/MY/y98UUecVL6g9BGqfzXyzUPE7fuOPZRUh2uvuhD7/zNiwaB/HivlxNrsFhS0Fd4kpzeuR3eA6ypCJVuP9j1RF9VHMmJGjTjeY5rvf8Q/AxPTxKxglsgeQaW3et1etjKjFnTX1v1w+6M8wCvY1YyB84iq809Sc097Vef8J3p3+MLkuKVZkWj7gsBFRhuxV8rE1DRPW01dLIB4x1k/KxDX9Fk30bES07xbzuAnovP/mrU3A/QcsGeWXdb8Euk/Gwdlf1pdFVabu9yzF2nfmGestJidC8svpAnPuB2LB2jfYBQDAipna28PRbrlwmjnfiK9qZvrgsOk/c/XfpVZpQDsinP0OcG2lz/TrycWGaGQpkrozgeyALeO5jR85c6r6PkoAK/KL6w5OCpE49WDoZm9uhG7OofnXBiv0odd+/UxPAckYFEsxSH5oE7Z0EeCc8+u/ujepXt93ssMZLp8EyLNZvScXjpOJMbsuO012KovhA1lfwYk6eDdWAgO37AVYG+lXAuAvKY8dyaxaYqE1jgsg=
